import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'package:money_lens/models/split_recurring_template.dart';
import 'package:money_lens/providers/transaction_provider.dart';

void main() {
  setUp(() {
    SharedPreferences.setMockInitialValues({});
  });

  Future<TransactionProvider> seededProvider() async {
    final provider = TransactionProvider();
    await provider.addSplitPerson('Alice');
    await provider.addSplitPerson('Bob');
    return provider;
  }

  bool sameDay(DateTime a, DateTime b) {
    return a.year == b.year && a.month == b.month && a.day == b.day;
  }

  test('weekly recurring catch-up creates missing occurrences in order',
      () async {
    final provider = await seededProvider();
    final aliceId =
        provider.splitPeople.firstWhere((p) => p.name == 'Alice').id;
    final bobId = provider.splitPeople.firstWhere((p) => p.name == 'Bob').id;

    await provider.addRecurringTemplate(
      title: 'Weekly groceries',
      amount: 700,
      paidByPersonId: aliceId,
      participantWeights: {
        aliceId: 1,
        bobId: 1,
      },
      frequency: SplitRecurringFrequency.weekly,
      startDate: DateTime(2026, 1, 1),
    );

    final template = provider.splitRecurringTemplates.first;
    await provider.runRecurringCatchUp(DateTime(2026, 1, 22));

    final generated = provider.splitExpenses
        .where((e) => e.sourceTemplateId == template.id)
        .toList()
      ..sort((a, b) => a.occurrenceDate!.compareTo(b.occurrenceDate!));

    expect(generated.length, 4);
    expect(generated.every((e) => e.isAutoGenerated), isTrue);
    expect(sameDay(generated[0].occurrenceDate!, DateTime(2026, 1, 1)), isTrue);
    expect(
        sameDay(generated[3].occurrenceDate!, DateTime(2026, 1, 22)), isTrue);

    final updatedTemplate =
        provider.splitRecurringTemplates.firstWhere((t) => t.id == template.id);
    expect(sameDay(updatedTemplate.nextRunAt, DateTime(2026, 1, 29)), isTrue);
  });

  test('monthly recurring handles month-end safely', () async {
    final provider = await seededProvider();
    final aliceId =
        provider.splitPeople.firstWhere((p) => p.name == 'Alice').id;
    final bobId = provider.splitPeople.firstWhere((p) => p.name == 'Bob').id;

    await provider.addRecurringTemplate(
      title: 'Rent',
      amount: 30000,
      paidByPersonId: aliceId,
      participantWeights: {
        aliceId: 1,
        bobId: 1,
      },
      frequency: SplitRecurringFrequency.monthly,
      startDate: DateTime(2026, 1, 31),
    );

    final templateId = provider.splitRecurringTemplates.first.id;
    await provider.runRecurringCatchUp(DateTime(2026, 3, 31));

    final occurrences = provider.splitExpenses
        .where((e) => e.sourceTemplateId == templateId)
        .map((e) => e.occurrenceDate!)
        .toList()
      ..sort();

    expect(occurrences.length, 3);
    expect(sameDay(occurrences[0], DateTime(2026, 1, 31)), isTrue);
    expect(sameDay(occurrences[1], DateTime(2026, 2, 28)), isTrue);
    expect(sameDay(occurrences[2], DateTime(2026, 3, 31)), isTrue);
  });

  test('this-and-future edit updates only future generated occurrences',
      () async {
    final provider = await seededProvider();
    final aliceId =
        provider.splitPeople.firstWhere((p) => p.name == 'Alice').id;
    final bobId = provider.splitPeople.firstWhere((p) => p.name == 'Bob').id;

    await provider.addRecurringTemplate(
      title: 'House bills',
      amount: 1000,
      paidByPersonId: aliceId,
      participantWeights: {
        aliceId: 1,
        bobId: 1,
      },
      frequency: SplitRecurringFrequency.weekly,
      startDate: DateTime(2026, 1, 1),
    );

    final templateId = provider.splitRecurringTemplates.first.id;
    await provider.runRecurringCatchUp(DateTime(2026, 1, 22));

    await provider.updateRecurringTemplateThisAndFuture(
      templateId: templateId,
      effectiveFrom: DateTime(2026, 1, 15),
      title: 'House bills updated',
      amount: 1500,
      frequency: SplitRecurringFrequency.weekly,
    );
    await provider.runRecurringCatchUp(DateTime(2026, 1, 29));

    final occurrences = provider.splitExpenses
        .where((e) => e.sourceTemplateId == templateId)
        .toList()
      ..sort((a, b) => a.occurrenceDate!.compareTo(b.occurrenceDate!));

    expect(occurrences.length, 5);

    final oldDates = [DateTime(2026, 1, 1), DateTime(2026, 1, 8)];
    for (final date in oldDates) {
      final expense =
          occurrences.firstWhere((e) => sameDay(e.occurrenceDate!, date));
      expect(expense.amount, 1000);
    }

    final newDates = [
      DateTime(2026, 1, 15),
      DateTime(2026, 1, 22),
      DateTime(2026, 1, 29),
    ];
    for (final date in newDates) {
      final expense =
          occurrences.firstWhere((e) => sameDay(e.occurrenceDate!, date));
      expect(expense.amount, 1500);
      expect(expense.title, 'House bills updated');
    }
  });

  test('pause and resume control auto-generation', () async {
    final provider = await seededProvider();
    final aliceId =
        provider.splitPeople.firstWhere((p) => p.name == 'Alice').id;
    final bobId = provider.splitPeople.firstWhere((p) => p.name == 'Bob').id;

    await provider.addRecurringTemplate(
      title: 'Internet',
      amount: 1000,
      paidByPersonId: aliceId,
      participantWeights: {
        aliceId: 1,
        bobId: 1,
      },
      frequency: SplitRecurringFrequency.weekly,
      startDate: DateTime(2026, 1, 1),
    );

    final templateId = provider.splitRecurringTemplates.first.id;
    await provider.pauseRecurringTemplate(templateId);
    await provider.runRecurringCatchUp(DateTime(2026, 1, 22));
    expect(provider.splitExpenses, isEmpty);

    await provider.resumeRecurringTemplate(templateId);
    await provider.runRecurringCatchUp(DateTime(2026, 1, 22));

    final generated = provider.splitExpenses
        .where((e) => e.sourceTemplateId == templateId)
        .toList();
    expect(generated.length, 4);
  });

  test('invalid member in recurring template is paused with warning', () async {
    final provider = await seededProvider();
    final aliceId =
        provider.splitPeople.firstWhere((p) => p.name == 'Alice').id;
    final bobId = provider.splitPeople.firstWhere((p) => p.name == 'Bob').id;

    await provider.addRecurringTemplate(
      title: 'Subscription',
      amount: 500,
      paidByPersonId: aliceId,
      participantWeights: {
        aliceId: 1,
        bobId: 1,
      },
      frequency: SplitRecurringFrequency.weekly,
      startDate: DateTime(2026, 1, 1),
    );

    await provider.removeSplitPerson(bobId);
    await provider.runRecurringCatchUp(DateTime(2026, 1, 22));

    final template = provider.splitRecurringTemplates.first;
    expect(template.isActive, isFalse);
    expect((template.pauseReason ?? '').isNotEmpty, isTrue);

    final generated = provider.splitExpenses
        .where((e) => e.sourceTemplateId == template.id)
        .toList();
    expect(generated, isEmpty);
  });

  test('catch-up generation is capped per run to prevent runaway loops',
      () async {
    final provider = await seededProvider();
    final aliceId =
        provider.splitPeople.firstWhere((p) => p.name == 'Alice').id;
    final bobId = provider.splitPeople.firstWhere((p) => p.name == 'Bob').id;

    await provider.addRecurringTemplate(
      title: 'Weekly pooled expense',
      amount: 250,
      paidByPersonId: aliceId,
      participantWeights: {
        aliceId: 1,
        bobId: 1,
      },
      frequency: SplitRecurringFrequency.weekly,
      startDate: DateTime(2020, 1, 1),
    );

    final templateId = provider.splitRecurringTemplates.first.id;
    await provider.runRecurringCatchUp(DateTime(2026, 1, 1));

    final generated = provider.splitExpenses
        .where((e) => e.sourceTemplateId == templateId)
        .toList();
    expect(generated.length, 24);
  });
}
