class SplitExpense {
  final String id;
  final String title;
  final double amount;
  final String paidByPersonId;
  final Map<String, double> participantWeights;
  final DateTime createdAt;
  final String? sourceTemplateId;
  final DateTime? occurrenceDate;
  final bool isAutoGenerated;

  const SplitExpense({
    required this.id,
    required this.title,
    required this.amount,
    required this.paidByPersonId,
    required this.participantWeights,
    required this.createdAt,
    this.sourceTemplateId,
    this.occurrenceDate,
    this.isAutoGenerated = false,
  });

  int get participantCount => participantWeights.length;

  SplitExpense copyWith({
    String? id,
    String? title,
    double? amount,
    String? paidByPersonId,
    Map<String, double>? participantWeights,
    DateTime? createdAt,
    String? sourceTemplateId,
    DateTime? occurrenceDate,
    bool? isAutoGenerated,
    bool clearSourceTemplateId = false,
    bool clearOccurrenceDate = false,
  }) {
    return SplitExpense(
      id: id ?? this.id,
      title: title ?? this.title,
      amount: amount ?? this.amount,
      paidByPersonId: paidByPersonId ?? this.paidByPersonId,
      participantWeights: participantWeights ?? this.participantWeights,
      createdAt: createdAt ?? this.createdAt,
      sourceTemplateId: clearSourceTemplateId
          ? null
          : (sourceTemplateId ?? this.sourceTemplateId),
      occurrenceDate:
          clearOccurrenceDate ? null : (occurrenceDate ?? this.occurrenceDate),
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'title': title,
        'amount': amount,
        'paidByPersonId': paidByPersonId,
        'participantWeights': participantWeights,
        'createdAt': createdAt.toIso8601String(),
        'sourceTemplateId': sourceTemplateId,
        'occurrenceDate': occurrenceDate?.toIso8601String(),
        'isAutoGenerated': isAutoGenerated,
      };

  factory SplitExpense.fromJson(Map<String, dynamic> json) {
    final rawWeights =
        Map<String, dynamic>.from((json['participantWeights'] as Map?) ?? {});
    final weights = rawWeights.map((key, value) {
      return MapEntry(key, (value as num?)?.toDouble() ?? 0);
    });

    return SplitExpense(
      id: json['id']?.toString() ?? '',
      title: json['title']?.toString() ?? '',
      amount: (json['amount'] as num?)?.toDouble() ?? 0,
      paidByPersonId: json['paidByPersonId']?.toString() ?? '',
      participantWeights: weights,
      createdAt: DateTime.tryParse(json['createdAt']?.toString() ?? '') ??
          DateTime.now(),
      sourceTemplateId: json['sourceTemplateId']?.toString(),
      occurrenceDate:
          DateTime.tryParse(json['occurrenceDate']?.toString() ?? ''),
      isAutoGenerated: json['isAutoGenerated'] is bool
          ? json['isAutoGenerated'] as bool
          : false,
    );
  }
}
