
import json
import re
import os
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# 1. Load Dataset
data_path = 'data/kaggle_indian_bank_sms_dataset.jsonl'
texts = []
labels = []

with open(data_path, 'r') as f:
    for line in f:
        row = json.loads(line)
        texts.append(row['raw_sms'])
        labels.append(1 if row['is_financial_transaction'] == 1 else 0)

# 2. Train Model
vectorizer = CountVectorizer(lowercase=True, binary=True, max_features=500)
X = vectorizer.fit_transform(texts)
clf = MultinomialNB()
clf.fit(X, labels)

# 3. Export to Dart (Improved with Log-Ratios)
def generate_dart(vectorizer, clf):
    vocab = vectorizer.vocabulary_
    sorted_vocab = sorted(vocab.items(), key=lambda x: x[1])
    words = [x[0] for x in sorted_vocab]
    
    # NB Params: log(P(x|c))
    log_probs_1 = clf.feature_log_prob_[1] 
    log_probs_0 = clf.feature_log_prob_[0]
    
    # Log-Ratio: log(P(x|1)) - log(P(x|0))
    # Positive means the word is more likely to appear in a financial SMS
    ratios = log_probs_1 - log_probs_0
    
    dart_code = f"""// lib/services/inhouse_model_weights.dart
// GENERATED BY scripts/train_model.py
// A simple Naive Bayes log-ratio scoring system.

class InhouseModelWeights {{
  static const Map<String, double> weights = {{
"""
    for word, ratio in zip(words, ratios):
        if abs(ratio) > 0.3: # Only keep words with some signal
            dart_code += f"    '{word}': {ratio:.4f},\n"
            
    # Intercept = log(P(1)) - log(P(0))
    intercept = clf.class_log_prior_[1] - clf.class_log_prior_[0]
    
    dart_code += f"""  }};

  static const double intercept = {intercept:.4f};
  
  /// Scores a body of text. Positive = Financial, Negative = Other.
  static double score(String text) {{
    double total = intercept;
    final tokens = text.toLowerCase().split(RegExp(r'[^a-z0-9]'));
    final seen = <String>{{}};
    
    for (var token in tokens) {{
      if (token.length < 2) continue;
      if (seen.contains(token)) continue;
      if (weights.containsKey(token)) {{
        total += weights[token]!;
        seen.add(token);
      }}
    }}
    return total;
  }}
}}
"""
    return dart_code

# Write to file
dart_content = generate_dart(vectorizer, clf)
output_path = 'lib/services/inhouse_model_weights.dart'
with open(output_path, 'w') as f:
    f.write(dart_content)

print(f"Model trained on {len(texts)} samples. Exported to {output_path}")
